name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pandas=2.2.2
  - scikit-learn
  - pytest=8.3.2
  - requests==2.32.3
  - fastapi=0.112.0
  - uvicorn=0.20.0
  - gunicorn=22.0.0
  - pip=22.0.2
